#!/bin/bash
#This section runs NMAP scans of all IPs provided with a ping scan first then adds to an IP listing, then it finds specific ports of interest and then runs a complet scan as well.
echo "Enter Your IP"
read IP

echo "Company Name"
read Name

echo "Path to save folder"
read path

cd $HOME
if [ ! -d "$path/Nmap-$Name" ];then
    mkdir "$path/Nmap-$Name" 
fi

# Perform a Ping Scan
nmap -sP -oG - $IP | grep Host | cut -d' '   -f  2 | sort -u > "/$path/Nmap-$Name/NmapAliveIPs.txt"

#run a complete scan just in case!
#nmap -A -O -Pn -p- -iL "/$path/Nmap-$Name/NmapAliveIPs.txt" -oN  "/$path/Nmap-$Name/NmapIPAll.txt"

#Running for eyewitness. Eventually the complete scan will just parse out and input the file.
#nmap -p 22 -oG - $IP  | awk '/80/open/ {print $2}'
nmap -p 80 -oG - $IP | grep Host | cut -d' ' -f 2 | sort -u > "/$path/Nmap-$Name/scanMe.txt"


#running eyewitness
cd "/$path/Nmap-$Name/" && eyewitness -f 'scanMe.txt' --no-prompt 

chmod 777 $path/Nmap-$Name
chmod 777 $path/Nmap-$Name/*
