#!/bin/bash
#This section runs NMAP scans of all IPs provided with a ping scan first then adds to an IP listing, then it finds specific ports of interest and then runs a complet scan as well.
echo "Enter Your IP"
read IP

echo "Company Name"
read Name
cd $HOME
if [ ! -d "/$HOME/Desktop/Nmap-$Name" ];then
    mkdir "/$HOME/Desktop/Nmap-$Name" 
fi

# Perform a Ping Scan
nmap -sP $IP -oN "/$HOME/Desktop/Nmap-$Name/NmapPingScan.txt" 

# Grep out the ping scan for the IPs and output to a text file to scan next stages
grep -E -o "(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?).(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?).(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?).(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)" "/$HOME/Desktop/Nmap-$Name/NmapPingScan.txt" | sort -u >>"/$HOME/Desktop/Nmap-$Name/NmapIPsAlive.txt" 

# remove the old ping scan text
rm -r "/$HOME/Desktop/Nmap-$Name/NmapPingScan.txt" 

#run a low hanging fruit command
nmap -A -p 21,22,23,25,139,53,80,443,445,8080,8443,69 -Pn -iL "/$HOME/Desktop/Nmap-$Name/NmapIPsAlive.txt" -oN "/$HOME/Desktop/Nmap-$Name/NmapLowHangingFruit.txt"

#run a complete scan just in case!
 sudo nmap -A -O -Pn -p- -iL "/$HOME/Desktop/Nmap-$Name/NmapIPsAlive.txt" -oN  "/$HOME/Desktop/Nmap-$Name/NmapIPAll.txt"
