#!/bin/bash
#This section identifies your IP range to scan.
echo "Enter Your IP"
read IP

# Perform a Ping Scan
nmap -sP $IP -oN "/home/kali/Desktop/Engagement/NmapPingScan.txt" 

# Grep out the ping scan for the IPs and output to a text file to scan next stages
grep -E -o "(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)" "/home/kali/Desktop/Engagement/NmapPingScan.txt" | sort -u >>"/home/kali/Desktop/Engagement/NmapIPsAlive.txt" 

# remove the old ping scan text
rm -r "/home/kali/Desktop/Engagement/NmapPingScan.txt" 

#run a low hanging fruit command
nmap -A -p 21,22,23,25,139,53,80,443,445,8080,8443,69 -Pn -iL "/home/kali/Desktop/Engagement/NmapIPsAlive.txt" -oN "/home/kali/Desktop/Engagement/NmapLowHangingFruit.txt"

#run a complete scan just in case!
 sudo nmap -A -O -Pn -p- -iL "/home/kali/Desktop/Engagement/NmapIPsAlive.txt" -oN  "/home/kali/Desktop/Engagement/NmapIPAll.txt"

 chmod 777 /home/kali/Desktop/Engagement/*
 
 #WHAT I WANT IT TO DO
 #resolve IP addresses to websites
 #run eyewitness on all websites
 nmap -p80 -Pn $IP -oG "home/kali/Desktop/Engagement/NMAPHTTP.txt"
 
 grep -E -o "(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)" "/home/kali/Desktop/Engagement/NmapPingScan.txt" | sort -u >>"/home/kali/Desktop/Engagement/NmapHttp2.txt" 
 
 rm -r "home/kali/Desktop/Engagement/NMAPHTTP.txt"
 
 eyewitness --web -f "/home/kali/Desktop/Engagement/NmapHttp2.txt" --resolve --no-prompt 
