#!/bin/bash
#This section identifies your IP range to scan.
echo "Enter Your IP"
read IP

echo "Company Name"
read Name

if [ ! -d "/home/kali/Desktop/Engagement-$Name" ];then
	mkdir "/home/kali/Desktop/Engagement-$Name" 
fi

# Perform a Ping Scan
nmap -sP $IP -oN "/home/kali/Desktop/Engagement-$Name/NmapPingScan.txt" 

# Grep out the ping scan for the IPs and output to a text file to scan next stages
grep -E -o "(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)" "/home/kali/Desktop/Engagement-$Name/NmapPingScan.txt" | sort -u >>"/home/kali/Desktop/Engagement-$Name/NmapIPsAlive.txt" 

# remove the old ping scan text
rm -r "/home/kali/Desktop/Engagement-$Name/NmapPingScan.txt" 

#run a low hanging fruit command
nmap -A -p 21,22,23,25,139,53,80,443,445,8080,8443,69 -Pn -iL "/home/kali/Desktop/Engagement-$Name/NmapIPsAlive.txt" -oN "/home/kali/Desktop/Engagement-$Name/NmapLowHangingFruit.txt"

#run a complete scan just in case!
 sudo nmap -A -O -Pn -p- -iL "/home/kali/Desktop/Engagement-$Name/NmapIPsAlive.txt" -oN  "/home/kali/Desktop/Engagement-$Name/NmapIPAll.txt"
 

 #WHAT I WANT IT TO DO
 #resolve IP addresses to websites
 #run eyewitness on all websites
 nmap -p80 -Pn $IP -oG "/home/kali/Desktop/Engagement-$Name/NMAPHTTP.txt"
 
 chmod 777 /home/kali/Desktop/Engagement-$Name/*
 grep -E -o "(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)" "/home/kali/Desktop/Engagement-$Name/NMAPHTTP.txt"" | sort -u >>"/home/kali/Desktop/Engagement-$Name/NmapHttp2.txt" 
 
 rm -r "/home/kali/Desktop/Engagement-$Name/NMAPHTTP.txt"
 
 eyewitness --web -f "/home/kali/Desktop/Engagement-$Name/NmapHttp2.txt" --resolve --no-prompt 
