#!/bin/bash
#This section runs NMAP scans of all IPs provided with a ping scan first then adds to an IP listing, then it finds specific ports of interest and then runs a complet scan as well.
echo "Enter Your IP"
read IP

echo "Company Name"
read Name

echo "Path to save folder"
read path

cd $HOME
if [ ! -d "$path/Nmap-$Name" ];then
    mkdir "$path/Nmap-$Name" 
fi

# Perform a Ping Scan
nmap -sP $IP -oG "/$path/Nmap-$Name/NmapPingScan.txt" 

# Grep out the ping scan for the IPs and output to a text file to scan next stages
cat "/$path/Nmap-$Name/NmapPingScan.txt" | grep Host | cut -d' '  -f 2 | sort -u > "/$path/Nmap-$Name/NmapAliveIPs.txt"

# remove the old ping scan text
rm -r "/$path/Nmap-$Name/NmapPingScan.txt" 

#run a low hanging fruit command
nmap -A -p 21,22,23,25,139,53,80,443,445,8080,8443,69 -Pn -iL "/$path/Nmap-$Name/NmapAliveIPs.txt" -oN "/$path/Nmap-$Name/NmapLowHangingFruit.txt"

#run a complete scan just in case!
sudo nmap -A -O -Pn -p- -iL "/$path/Nmap-$Name/NmapAliveIPs.txt" -oN  "/$path/Nmap-$Name/NmapIPAll.txt"


chmod 777 $path/Nmap-$Name
chmod 777 $path/Nmap-$Name/*
